export const Gents={
    title:'Mens Wear',
    image1:'iamges/men/men 1.jpg',
    image2:'iamges/men/men2.jpg',
    image3:'iamges/men/men 3.jpg',
    image4:'iamges/men/men 4.jpeg',
    image5:'iamges/men/men 5.jpg',
    image6:'iamges/men/men 6.jpeg',
    price1:'699 INR',
    price2:'799 INR',
    price3:'999 INR',
    price4:'1099 INR',
    price5:'1199 INR',
    price6:'1299 INR',
}
export const Ladies={
    title:'Womens Wear',
    image1:'iamges/women/women 1.jpeg',
    image2:'iamges/women/women 2.jpeg',
    image3:'iamges/women/women 3.jpeg',
    image4:'iamges/women/women 4.jpeg',
    image5:'iamges/women/women 5.jpeg',
    image6:'iamges/women/women 6.jpeg',
    price1:'1599 INR',
    price2:'1699 INR',
    price3:'1799 INR',
    price4:'1899 INR',
    price5:'1999 INR',
    price6:'2099 INR',
}